# Generated by Django 6.0.1 on 2026-03-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_city_order_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
