# Generated by Django 6.0.1 on 2026-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар до товару'),
        ),
    ]
