# Generated by Django 6.0.1 on 2026-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ім’я')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('text', models.TextField(max_length=2000, verbose_name='Відгук')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Показувати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
