# Generated by Django 6.0.1 on 2026-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('out_of_stock', 'Немає в наявності')], default='in_stock', max_length=20, verbose_name='Наявність'),
        ),
    ]
