# Generated by Django 6.0.1 on 2026-03-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_stock_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=100, verbose_name='Колір')),
                ('size_name', models.CharField(blank=True, max_length=100, verbose_name='Розмір')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('out_of_stock', 'Немає в наявності')], default='in_stock', max_length=20, verbose_name='Наявність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Варіант товару',
                'verbose_name_plural': 'Варіанти товарів',
                'ordering': ['product', 'color_name', 'size_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('color_label', models.CharField(blank=True, max_length=100, verbose_name='Підпис кольору')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Фото варіанту',
                'verbose_name_plural': 'Фото варіантів',
            },
        ),
    ]
